import { terrainType } from "../../functions/Objects"

export const hexTestMap = {
    name:"Devil's Arena",
    shape:"hx",
    dimensions: "4x4x4",
    map:[
            [
                {id:100,image:null},
                {id:110,image:null},
                {id:"a01", image:"planes", move_in:1,is_cover:false,is_starting_position:false},
                {id:"b01", image:"planes", move_in:1,is_cover:false,is_starting_position:false},
                {id:"c01", image:"planes", move_in:1,is_cover:false,is_starting_position:false},
                {id:"d01", image:"planes", move_in:1,is_cover:false,is_starting_position:false}
            ],
            [
                {id:140,image:null},
                {id:"a02", image:"planes", move_in:1,is_cover:false,is_starting_position:false}, 
                {id:"b02", image:"planes", move_in:1,is_cover:false,is_starting_position:false}, 
                {id:"c02", image:"planes", move_in:1,is_cover:false,is_starting_position:false}, 
                {id:"d02", image:"planes", move_in:1,is_cover:false,is_starting_position:false}, 
                {id:"e02", image:"planes", move_in:1,is_cover:false,is_starting_position:false}
            ], 
            [
                {id:200,image:null},
                {id:"a03", image:"planes", move_in:1,is_cover:false,is_starting_position:false},
                {id:"b03", image:"planes", move_in:1,is_cover:false,is_starting_position:false},
                {id:"c03", image:"planes", move_in:1,is_cover:false,is_starting_position:false},
                {id:"d03", image:"planes", move_in:1,is_cover:false,is_starting_position:false},
                {id:"e03", image:"planes", move_in:1,is_cover:false,is_starting_position:false},
                {id:"f03", image:"planes", move_in:1,is_cover:false,is_starting_position:false},
            ],

            [
                {id:"a04", image:"planes", move_in:1,is_cover:false,is_starting_position:false}, 
                {id:"b04", image:"planes", move_in:1,is_cover:false,is_starting_position:false}, 
                {id:"c04", image:"planes", move_in:1,is_cover:false,is_starting_position:false}, 
                {id:"d04", image:"planes", move_in:1,is_cover:false,is_starting_position:false}, 
                {id:"e04", image:"planes", move_in:1,is_cover:false,is_starting_position:false}, 
                {id:"f04", image:"planes", move_in:1,is_cover:false,is_starting_position:false}, 
                {id:"g04", image:"planes", move_in:1,is_cover:false,is_starting_position:false}
            ],
            [
                {id:230,image:null}, 
                {id:"b05", image:"planes", move_in:1,is_cover:false,is_starting_position:false}, 
                {id:"c05", image:"planes", move_in:1,is_cover:false,is_starting_position:false}, 
                {id:"d05", image:"planes", move_in:1,is_cover:false,is_starting_position:false}, 
                {id:"e05", image:"planes", move_in:1,is_cover:false,is_starting_position:false}, 
                {id:"f05", image:"planes", move_in:1,is_cover:false,is_starting_position:false}, 
                {id:"g05", image:"planes", move_in:1,is_cover:false,is_starting_position:false}, 
            ], 
            [
                {id:240,image:null}, 
                {id:"c06", image:"planes", move_in:1,is_cover:false,is_starting_position:false}, 
                {id:"d06", image:"planes", move_in:1,is_cover:false,is_starting_position:false}, 
                {id:"e06", image:"planes", move_in:1,is_cover:false,is_starting_position:false}, 
                {id:"f06", image:"planes", move_in:1,is_cover:false,is_starting_position:false}, 
                {id:"g06", image:"planes", move_in:1,is_cover:false,is_starting_position:false}, 

            ],
            [
                {id:280,image:null},
                {id:290,image:null},
                {id:"d07", image:"planes", move_in:1,is_cover:false,is_starting_position:false},
                {id:"e07", image:"planes", move_in:1,is_cover:false,is_starting_position:false}, 
                {id:"f07", image:"planes", move_in:1,is_cover:false,is_starting_position:false}, 
                {id:"g07", image:"planes", move_in:1,is_cover:false,is_starting_position:false}
            ] 
        ],
    maxPlayers: 2
    }

export const miniMapHx = {
        name:"the mini hex",
        shape:"hx",
        dimensions:"3x3x3",
        map:[
                [
                    {
                        id:330,
                        image:null,
                        move_in:null,
                        cover:null,
                        is_starting_position:null,
                        posY:null,
                        posX:null,
                        owned_by:null,
                        objective:false,
                        formation:null,
                    },
                    {
                        id:"a01",
                        image:"planes",
                        move_in:1,
                        cover:false,
                        is_starting_position:false,
                        posY:null,
                        posX:null,
                        owned_by:null,
                        objective:true,
                        formation:null,
                    },
                {
                    id:"b01",
                    image:"planes",
                    move_in:1,
                    cover:false,
                    is_starting_position:false,
                    posY:null,
                    posX:null,
                    owned_by:null,
                    objective:null,
                    formation:null,
    
                },
                {
                    id:"c01",
                    image:"planes",
                    move_in:1,
                    cover:false,
                    is_starting_position:false,
                    posY:null,
                    posX:null,
                    owned_by:null,
                    objective:true,
                    formation:null,
                }
            ],
            [
                {
                    id:"a02",
                    image:"swamp",
                    move_in:1,
                    cover:false,
                    is_starting_position:false,
                    posY:null,
                    posX:null,
                    owned_by:null,
                    objective:false,
                    formation:null,
                },
                {
                    id:"b02",
                    image:"forest",
                    move_in:1,
                    cover:false,
                    is_starting_position:false,
                    posY:null,
                    posX:null,
                    owned_by:null,
                    objective:null,
                    formation:null,
                },
                {
                    id:"c02",
                    image:"forest",
                    move_in:1,
                    cover:false,
                    is_starting_position:false,
                    posY:null,
                    posX:null,
                    owned_by:null,
                    objective:null,
                    formation:null,
                },
                {
                    id:"d02",
                    image:"swamp",
                    move_in:1,
                    cover:false,
                    is_starting_position:false,
                    posY:null,
                    posX:null,
                    owned_by:null,
                    objective:null,
                    formation:null,
                }
            ],
            [
                {
                    id:"a03",
                    image:"hills",
                    move_in:1,
                    cover:false,
                    is_starting_position:true,
                    posY:null,
                    posX:null,
                    owned_by:'red',
                    objective:null,
                    formation:null,
                },
                {
                    id:"b03",
                    image:"swamp",
                    move_in:1,
                    cover:false,
                    is_starting_position:false,
                    posY:null,
                    posX:null,
                    owned_by:null,
                    objective:null,
                    formation:null,
                },
                {
                    id:"c03",
                    image:"mountains",
                    move_in:null,
                    cover:false,
                    is_starting_position:false,
                    posY:null,
                    posX:null,
                    owned_by:null,
                    objective:null,
                    formation:null,
                },
                {
                    id:"d03",
                    image:"swamp",
                    move_in:1,
                    cover:false,
                    is_starting_position:false,
                    posY:null,
                    posX:null,
                    owned_by:null,
                    objective:null,
                    formation:null,
                },
                {
                    id:"e03",
                    image:"hills",
                    move_in:1,
                    cover:false,
                    is_starting_position:true,
                    posY:null,
                    posX:null,
                    owned_by:'blue',
                    objective:null,
                    formation:null,
                }
            ],
            [
                {
                    id:"b04",
                    image:"swamp",
                    move_in:1,
                    cover:false,
                    is_starting_position:false,
                    posY:null,
                    posX:null,
                    owned_by:null,
                    objective:null,
                    formation:null,
                },
                {
                    id:"c04",
                    image:"forest",
                    move_in:1,
                    cover:false,
                    is_starting_position:false,
                    posY:null,
                    posX:null,
                    owned_by:null,
                    objective:null,
                    formation:null,
                },
                {
                    id:"d04",
                    image:"forest",
                    move_in:1,
                    cover:false,
                    is_starting_position:false,
                    posY:null,
                    posX:null,
                    owned_by:null,
                    objective:null,
                    formation:null,
                },
                {
                    id:"e04",
                    image:"swamp",
                    move_in:1,
                    cover:false,
                    is_starting_position:false,
                    posY:null,
                    posX:null,
                    owned_by:null,
                    objective:null,
                    formation:null,
                }
            ],

            [
                {
                    id:500,
                    image:null,
                    move_in:null,
                    cover:null,
                    is_starting_position:null,
                    posY:null,
                    posX:null,
                    owned_by:null,
                    objective:null,
                    formation:null,
                },
                {
                    id:"c05",
                    image:"planes",
                    move_in:1,
                    cover:false,
                    is_starting_position:false,
                    posY:null,
                    posX:null,
                    owned_by:null,
                    objective:true,
                    formation:null,
                },
                {
                    id:"d05",
                    image:"planes",
                    move_in:1,
                    cover:false,
                    is_starting_position:false,
                    posY:null,
                    posX:null,
                    owned_by:null,
                    objective:false,
                    formation:null,
                },
                {
                    id:"e05",
                    image:"planes",
                    move_in:1,
                    cover:false,
                    is_starting_position:false,
                    posY:null,
                    posX:null,
                    owned_by:null,
                    objective:true,
                    formation:null,

                }
            ]
        ],
        maxPlayers:2
    }